### PR TITLE
Read in project structure and more fixes to support reading in a project

### PR DESCRIPTION
**Pull request by ruijiefang**
Latest updates on the dev branch as of 8/16/2022.

### CODE REVIEW

**Comment by ruijiefang** [comment]
@hirataqdees I just added 1 commit: 
 - feature: make dependency analysis for changed AST nodes work on inter-module level for every toplevel module. This solves the issue of typecart only making very coarse-grained distinction of what changed and what didn't (before, if any sub-decl inside a toplevel module decl changed, the entire module is marked as changed. now, if a subdeclaration changes, we only mark that particular node as changed and mark the rest as unchanged.) This took a while to be implemented correctly because of some trickiness of working with YIL AST.
 - bugfix: I fixed a build error in testing harness `TypeInjections.Test` and the CI is now failing only because the tests are not going through. This is expected as the output behavior has changed.

**Comment by ruijiefang** [comment]
Two more commits: Rename `combine` file to `translations` file and clean up.

**Comment by ruijiefang** [comment]
Build is now passing with latest commit, which fixed the testing project.

**Review by hirataqdees — APPROVED** [review]
Ruijie and I reviewed the PR offline.

**Pull request merged**
